name: movie
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.0.6
  carousel_slider: ^0.0.7
  dio: ^3.0.10
  flutter_screenutil: ^0.5.1
  provider: ^5.0.0
  flutter_easyrefresh: ^2.1.5
  fluttertoast: ^3.0.3
  shared_preferences: ^0.4.1
  webview_flutter: ^0.3.10+4
  crypto: ^2.1.1+1
  flutter_easyloading: ^2.2.2
  image_picker: ^0.6.1+4
  audioplayers: ^0.16.1
  flutter_lyric: ^1.0.0
  fluro: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/assets/images/icon-hot.png
   - lib/assets/images/icon-classify.png
   - lib/assets/images/icon-top.png
   - lib/assets/images/icon-play.png
   - lib/assets/images/icon-app.png
   - lib/assets/images/icon-arrow.png
   - lib/assets/images/icon-collection.png
   - lib/assets/images/icon-collection-active.png
   - lib/assets/images/icon-music.png
   - lib/assets/images/icon-record.png
   - lib/assets/images/icon-talk.png
   - lib/assets/images/icon-detail-play.png
   - lib/assets/images/icon-empty-star.png
   - lib/assets/images/icon-full-star.png
   - lib/assets/images/icon-half-star.png
   - lib/assets/images/icon-comment.png
   - lib/assets/images/icon-share.png
   - lib/assets/images/icon-password.png
   - lib/assets/images/icon-user.png
   - lib/assets/images/icon-clear.png
   - lib/assets/images/icon-back.png
   - lib/assets/images/icon_edit.png
   - lib/assets/images/icon_play_record.png
   - lib/assets/images/icon-logo.png
   - lib/assets/images/icon-home.png
   - lib/assets/images/icon-home-active.png
   - lib/assets/images/icon-recomment.png
   - lib/assets/images/icon-recomment-active.png
   - lib/assets/images/icon-music-circle.png
   - lib/assets/images/icon-music-circle-active.png
   - lib/assets/images/icon-user.png
   - lib/assets/images/icon-user-active.png
   - lib/assets/images/icon-movie.png
   - lib/assets/images/icon-movie-active.png
   - lib/assets/images/icon-tv.png
   - lib/assets/images/icon-tv-active.png
   - lib/assets/images/icon-down.png
   - lib/assets/images/icon-music-singer.png
   - lib/assets/images/icon-music-classify.png
   - lib/assets/images/icon-music-classics.png
   - lib/assets/images/icon-music-rank.png
   - lib/assets/images/icon-music-play.png
   - lib/assets/images/icon-music-add.png
   - lib/assets/images/icon-music-menu.png
   - lib/assets/images/icon-no1.png
   - lib/assets/images/icon-no2.png
   - lib/assets/images/icon-no3.png
   - lib/assets/images/icon-like.png
   - lib/assets/images/icon-like-active.png
   - lib/assets/images/icon-music-like.png
   - lib/assets/images/icon-menu-board.png
   - lib/assets/images/icon-menu-collect.png
   - lib/assets/images/icon-menu-history.png
   - lib/assets/images/icon-menu-like.png
   - lib/assets/images/icon-menu-add.png
   - lib/assets/images/icon-delete.png
   - lib/assets/images/icon-music-collect.png
   - lib/assets/images/icon-music-down.png
   - lib/assets/images/icon-music-comments.png
   - lib/assets/images/icon-music-white-menu.png
   - lib/assets/images/icon-music-next.png
   - lib/assets/images/icon-music-prev.png
   - lib/assets/images/icon-music-order.png
   - lib/assets/images/icon-music-play-menu.png
   - lib/assets/images/icon-music-play-white.png
   - lib/assets/images/icon-music-playing.png
   - lib/assets/images/icon-music-playing-grey.png
   - lib/assets/images/icon-music-refresh.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: hot
      fonts:
        - asset: lib/assets/fonts/hot.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
